// js/pages/affine.js:
import { qs, parseNumber } from "../shared/dom.js";
import { View2D } from "../shared/view2D.js";
import { exportCanvasPNG } from "../shared/exportMedia.js";
import { DimensionLab } from "../shared/dimension/index.js";
import { typesetMath } from "../shared/mathjax.js";

const canvas = qs("#affineCanvas");
const ctx = canvas.getContext("2d", { alpha: true });
const statusReadout = qs("#statusReadout");

const UI = {
    mapCount: () => qs("#mapCount"),
    numPoints: () => qs("#numPoints"),
    exampleSelector: () => qs("#exampleSelector"),

    // Affine matrix/probability controls
    matrixWrap: () => qs("#matrixAInputsContainer"),
    vectorWrap: () => qs("#vectorBInputsContainer"),
    probWrap: () => qs("#probabilitiesContainer"),
    probabilityMode: () => qs("#probabilityMode"),
    contractionWarnings: () => qs("#contractionWarnings"),

    generate: () => qs("#generateAffine"),
    reset: () => qs("#resetAffine"),
    export: () => qs("#exportAffine"),
    clearSteps: () => qs("#clearSteps"),

    stepOnce: () => qs("#stepOnce"),
    toggleAnim: () => qs("#toggleAnimation"),

    zoomIndicator: () => qs("#zoom-indicator"),
    mouseCoords: () => qs("#mouse-coords"),

    // Dimension controls
    dimMode: () => qs("#dimMode"),
    dimDownsample: () => qs("#dimDownsample"),
    dimMinBox: () => qs("#dimMinBox"),
    dimMaxBox: () => qs("#dimMaxBox"),
    dimSamples: () => qs("#dimSamples"),
    dimRunBtn: () => qs("#dimRunBtn"),
    dimValue: () => qs("#dimValue"),
    dimMeta: () => qs("#dimMeta"),
};

// Reference unit square for visualising each affine map
const REF = {
    p00: { x: 0, y: 0 },
    p10: { x: 1, y: 0 },
    p01: { x: 0, y: 1 },
    p11: { x: 1, y: 1 },
};

let view2d = null;
let affineMaps = [];
let cachedPoints = [];
let needsRegen = true;  // True when cachedPoints do not match current maps

let stepPoints = [];                // Stores points generated by step-by-step Chaos Game
let currentPoint = { x: 0, y: 0 };

// Animation state
let playing = false;
let rafId = null;

let dragCorner = null;  // { mapIndex, corner, keepWhich }
let hoverCorner = null;
let activeExampleName = "Sierpinski Triangle";  // Assumed example generated

const DEFAULT_VIEW = { xMin: -1.2, xMax: 2.2, yMin: -1.2, yMax: 2.2 };
// Each example has a sensible default window
const exampleViews = {
    "Barnsley Fern": { xMin: -3, xMax: 3, yMin: 0, yMax: 10 },
    "Sierpinski Triangle": { xMin: -0.25, xMax: 2.25, yMin: -0.25, yMax: 2 },
    "Sierpinski Carpet": { xMin: -0.2, xMax: 1.2, yMin: -0.2, yMax: 1.2 },
    "Shrinking Square": { xMin: -0.2, xMax: 1.2, yMin: -0.2, yMax: 1.2 },
    "Spiral": { xMin: -0.6, xMax: 1.8, yMin: -0.6, yMax: 1.8 },
    "Pentagon Star": { xMin: -1.7, xMax: 1.7, yMin: -1.7, yMax: 1.7 },
};

// Clamps integer in interval [a, b]
function clampInt(x, a, b) {
    return Math.max(a, Math.min(b, x | 0));
}
// Function calcualtes Euclidean distance between world-coordinate points
// Used for when mouse is close to draggable hanlde
function dist(p, q) { 
    return Math.hypot(p.x - q.x, p.y - q.y); 
}

// Chaos Game: random starting point
function randomSeedPoint() { 
    return { 
        // Initialising near reference square s.t. orbit settles quickly
        x: Math.random() * 1.4 - 0.2, 
        y: Math.random() * 1.4 - 0.2 
    }; 
}

// Function formats numbers neatly for input boxes and readouts
function fmt(x, places = 4) {
    if (!Number.isFinite(x)) {
        return "0";
    }
    const rounded = Number(x.toFixed(places));

    // Avoids displaying value "-0"
    return Object.is(rounded, -0) ? "0" : String(rounded);
}

// Function used to roughly measure how strongly each affine map contracts space
function spectralNorm(m) {
    // 2 x 2 matrix A
    const a = m.a11;
    const b = m.a12;
    const c = m.a21;
    const d = m.a22;

    // Eigevalue fomrula: A^T A
    const trace = a * a + b * b + c * c + d * d;
    const det = (a * d - b * c) ** 2;
    const disc = Math.max(0, trace * trace - 4 * det);

    // Returns estimated spectral norm of A
    return Math.sqrt(Math.max(0, (trace + Math.sqrt(disc)) / 2));
}

// Converts world coordinates -> canvas pixel coordinates
function worldToCanvas(x, y) {
    const v = view2d.view;
    const u = (x - v.xMin) / (v.xMax - v.xMin);
    const t = (v.yMax - y) / (v.yMax - v.yMin);

    return { 
        px: u * canvas.width, 
        py: t * canvas.height 
    };
}

// Converts mouse/pointer event -> canvas pixel coordinates
function clientToCanvasPx(e) {
    const rect = canvas.getBoundingClientRect();
    const cx = (e.clientX - rect.left) * (canvas.width / rect.width);
    const cy = (e.clientY - rect.top) * (canvas.height / rect.height);

    return { cx, cy };
}

// Converts fixed screen handle radius to world-coordinate size
function handleRadiusWorld() {
    const v = view2d.view;
    const worldW = v.xMax - v.xMin;

    // Keeps draggable handles easy to select at different zoom levels
    return (12 / canvas.width) * worldW;
}

// Function chooses clean grid step near x
function niceStep(x) {
    const p = Math.pow(10, Math.floor(Math.log10(x)));
    const a = x / p;

    // Ensures its a 'nice' step, e.g. 0.02 and not 0.037
    if (a < 1.5) return 1 * p;
    if (a < 3.5) return 2 * p;
    if (a < 7.5) return 5 * p;

    return 10 * p;
}

function ink(alpha = 0.95) {
    const inkVar = getComputedStyle(document.documentElement)
        .getPropertyValue("--ink")
        .trim();
    
    if (inkVar.startsWith("rgb(")) {
        return inkVar.replace("rgb(", "rgba(").replace(")", `,${alpha})`);  // Adds alpha transparency to rgb() colours
    }

    if (inkVar) {
        return inkVar;  // fallback (no alpha)
    }

    // Returns current theme ink colour
    return `rgba(20,20,20,${alpha})`;
}

// Preset IFS examples
const examples = {
    "Barnsley Fern": [
        { a11: 0, a12: 0, a21: 0, a22: 0.16, b1: 0, b2: 0, prob: 0.01 },
        { a11: 0.85, a12: 0.04, a21: -0.04, a22: 0.85, b1: 0, b2: 1.6, prob: 0.85 },
        { a11: 0.2, a12: -0.26, a21: 0.23, a22: 0.22, b1: 0, b2: 1.6, prob: 0.07 },
        { a11: -0.15, a12: 0.28, a21: 0.26, a22: 0.24, b1: 0, b2: 0.44, prob: 0.07 }
    ],

    "Sierpinski Triangle": [
        { a11: 0.5, a12: 0, a21: 0, a22: 0.5, b1: 0, b2: 0, prob: 1 / 3 },
        { a11: 0.5, a12: 0, a21: 0, a22: 0.5, b1: 1, b2: 0, prob: 1 / 3 },
        { a11: 0.5, a12: 0, a21: 0, a22: 0.5, b1: 0.5, b2: Math.sqrt(3) / 2, prob: 1 / 3 }
    ],

    "Sierpinski Carpet": [
        { a11: 1 / 3, a12: 0, a21: 0, a22: 1 / 3, b1: 0, b2: 0, prob: 1 / 8 },
        { a11: 1 / 3, a12: 0, a21: 0, a22: 1 / 3, b1: 1 / 3, b2: 0, prob: 1 / 8 },
        { a11: 1 / 3, a12: 0, a21: 0, a22: 1 / 3, b1: 2 / 3, b2: 0, prob: 1 / 8 },
        { a11: 1 / 3, a12: 0, a21: 0, a22: 1 / 3, b1: 0, b2: 1 / 3, prob: 1 / 8 },
        { a11: 1 / 3, a12: 0, a21: 0, a22: 1 / 3, b1: 2 / 3, b2: 1 / 3, prob: 1 / 8 },
        { a11: 1 / 3, a12: 0, a21: 0, a22: 1 / 3, b1: 0, b2: 2 / 3, prob: 1 / 8 },
        { a11: 1 / 3, a12: 0, a21: 0, a22: 1 / 3, b1: 1 / 3, b2: 2 / 3, prob: 1 / 8 },
        { a11: 1 / 3, a12: 0, a21: 0, a22: 1 / 3, b1: 2 / 3, b2: 2 / 3, prob: 1 / 8 }
    ],

    "Shrinking Square": [
        { a11: 0.42, a12: 0, a21: 0, a22: 0.42, b1: 0, b2: 0, prob: 0.25 },
        { a11: 0.42, a12: 0, a21: 0, a22: 0.42, b1: 0.58, b2: 0, prob: 0.25 },
        { a11: 0.42, a12: 0, a21: 0, a22: 0.42, b1: 0, b2: 0.58, prob: 0.25 },
        { a11: 0.42, a12: 0, a21: 0, a22: 0.42, b1: 0.58, b2: 0.58, prob: 0.25 }
    ],

    "Spiral": [
        { a11: 0.48, a12: -0.34, a21: 0.34, a22: 0.48, b1: 0, b2: 0, prob: 0.45 },
        { a11: 0.48, a12: 0.34, a21: -0.34, a22: 0.48, b1: 0.82, b2: 0.1, prob: 0.45 },
        { a11: 0.22, a12: 0, a21: 0, a22: 0.22, b1: 0.35, b2: 0.78, prob: 0.1 }
    ],

    "Pentagon Star": (() => {
        const maps = [];
        const n = 5;
        const angleStep = (2 * Math.PI) / n;
        
        // Places give small copies around the pentagon
        for (let i = 0; i < n; i++) {
            const angle = i * angleStep - Math.PI / 2;
            
            maps.push({
                a11: 0.382, 
                a12: 0,
                a21: 0, 
                a22: 0.382,
                b1: Math.cos(angle),
                b2: Math.sin(angle),
                prob: 1 / n
            });
        }

        return maps;
    })()
};

function applyAffine(p, m) {
    // Applies single affine map to point: f(x,y) = A(x,y) + b
    return { 
        x: m.a11 * p.x + m.a12 * p.y + m.b1, 
        y: m.a21 * p.x + m.a22 * p.y + m.b2 
    };
}

function chooseMap(maps) {
    // Random choice step in Chaos Game
    const r = Math.random();
    let acc = 0;

    // Chooses one affine map using stored probabilities
    for (const m of maps) {
        acc += m.prob;
        if (r <= acc) return m;
    }

    // Falback in case floating-point totals are slightly below 1
    return maps[maps.length - 1];
}

// Function generates IFS attractor using Chaos Game
function generateAffineFractal(maps, n = 10000, x0 = 0, y0 = 0, burnIn = 30) {
    if (!maps?.length) return [];

    const pts = [];
    let p = { x: x0, y: y0 };

    // Burn-in removes early points before orbit settles onto the attractor
    for (let i = 0; i < burnIn; i++) {
        p = applyAffine(p, chooseMap(maps));
    }

    // Main Chaos Game orbit
    for (let i = 0; i < n; i++) {
        p = applyAffine(p, chooseMap(maps));
        pts.push({ x: p.x, y: p.y });
    }

    return pts;
}

function imageParallelogram(m) {
    // Corners of f (REF square):
    const b = { x: m.b1, y: m.b2 };
    const c1 = { x: m.b1 + m.a11, y: m.b2 + m.a21 };
    const c2 = { x: m.b1 + m.a12, y: m.b2 + m.a22 };
    const c12 = { 
        x: m.b1 + m.a11 + m.a12, 
        y: m.b2 + m.a21 + m.a22 
    };

    // Computed image of reference unit square under one affine map
    // Four points are drawn as draggable parallelogram
    return { b, c1, c2, c12 };
}

// Function checks if world-coordinate mouse point is close to any draggable corner of any affine map parallelogram
function pickCorner(worldPt) {
    const r = handleRadiusWorld();
    
    for (let i = 0; i < affineMaps.length; i++) {
        const { b, c1, c2, c12 } = imageParallelogram(affineMaps[i]);

        // Using Euclidean distance function for calculations
        if (dist(worldPt, b) <= r) return { mapIndex: i, corner: "b" };
        if (dist(worldPt, c1) <= r) return { mapIndex: i, corner: "c1" };
        if (dist(worldPt, c2) <= r) return { mapIndex: i, corner: "c2" };
        if (dist(worldPt, c12) <= r) return { mapIndex: i, corner: "c12" };
    }
    
    return null;
}

// Function updates affine map when one of its visual handles is dragged
function applyCornerDrag(mapIndex, corner, newPosWorld, keepWhich = "c1") {
    const m = affineMaps[mapIndex];

    // Current reference square image
    const { b, c1, c2 } = imageParallelogram(m);

    // b changes translation
    if (corner === "b") {
        // Moving b translates whole affine image
        m.b1 = newPosWorld.x;
        m.b2 = newPosWorld.y;
        return;
    }

    // c1 changes first column of A
    if (corner === "c1") {
        // Moving c1 edits first column of A
        m.a11 = newPosWorld.x - b.x;
        m.a21 = newPosWorld.y - b.y;
        return;
    }

    // c2 changes second column of A
    if (corner === "c2") {
        // Moving c2 edits second column of A
        m.a12 = newPosWorld.x - b.x;
        m.a22 = newPosWorld.y - b.y;
        return;
    }

    // c12 changes one column while keeping other fixed
    if (corner === "c12") {
        // Opposite corner: changes one direction while keeping the other fixed
        const sx = newPosWorld.x - b.x;
        const sy = newPosWorld.y - b.y;

        if (keepWhich === "c2") {
            // Keeps c2 fixed and solves for c1
            const c2x = c2.x - b.x;
            const c2y = c2.y - b.y;

            m.a11 = sx - c2x;
            m.a21 = sy - c2y;
        } else {
            // Keeps c1 fixed and solves for c2
            const c1x = c1.x - b.x;
            const c1y = c1.y - b.y;

            m.a12 = sx - c1x;
            m.a22 = sy - c1y;
        }
    }
}

function normaliseProbs() {
    // Adds up all current probailities
    // Treats invalid values as 0
    const sum = affineMaps.reduce((s, m) => s + (+m.prob || 0), 0);

    // If total sum +ve, scales each probability s.t. they add up to 1
    if (sum > 0) {
        affineMaps.forEach(m => (m.prob = (+m.prob || 0) / sum));
    } else {
        // If all probabilities 0 or invalid, gives each map equal probability
      const p = 1 / Math.max(1, affineMaps.length);
      affineMaps.forEach(m => (m.prob = p));
    }
}

// Function applies selected probability mode
function applyProbabilityMode() {
    // "custom" = normalise user values
    const mode = UI.probabilityMode()?.value || "custom";
    if (!affineMaps.length || mode === "custom") {
        normaliseProbs();
        return;
    }

    // "equal" = eap map equally likely
    if (mode === "equal") {
        const p = 1 / affineMaps.length;
        affineMaps.forEach(m => (m.prob = p));
        return;
    }

    // "spectral" = weight maps by approximate matrix size
    if (mode === "spectral") {
        const weights = affineMaps.map(m => {
            const norm = spectralNorm(m);

            return Number.isFinite(norm) ? Math.max(norm, 0.0001) : 0.0001;
        });

        const sum = weights.reduce((s, w) => s + w, 0);
        affineMaps.forEach((m, i) => (m.prob = weights[i] / sum));
    }
}

// Function renders warnings about whetehr each affine map appears contractive
function renderContractionWarnings() {
    const wrap = UI.contractionWarnings();
    if (!wrap) return;
    wrap.replaceChildren();

    if (!affineMaps.length) {
        const empty = document.createElement("div");
        empty.className = "diagnostic";
        empty.textContent = "No maps to check.";
        wrap.appendChild(empty);
        return;
    }

    affineMaps.forEach((m, i) => {
        const norm = spectralNorm(m);
        const item = document.createElement("div");
        item.className = "diagnostic";

        // Catches maps which may blow up instead of forming an attractor
        if (norm >= 1) {
            item.classList.add("danger");
            item.textContent = `Map ${i + 1}: ||A|| approx ${fmt(norm)}. This map may not be contractive.`;
        } else if (norm > 0.5) {
            item.classList.add("warn");
            item.textContent = `Map ${i + 1}: ||A|| approx ${fmt(norm)}. Large contractions can give heavy overlap or filled regions.`;
        } else {
            item.textContent = `Map ${i + 1}: ||A|| approx ${fmt(norm)}. Contractive.`;
        }

        wrap.appendChild(item);
    });
}

function ensureMapsLength(n) {
    // Ensures affineMaps array has exactly n maps
    n = clampInt(Math.floor(n), 1, 10);
    while (affineMaps.length < n) {
        // Adds default maps if user increases map count
        affineMaps.push({ 
            a11: 0.5, a12: 0, 
            a21: 0, a22: 0.5, 
            b1: 0, b2: 0, 
            prob: 1 });
    }

    // Removes maps from end if user decreases map count
    while (affineMaps.length > n) {
        affineMaps.pop();
    }

    applyProbabilityMode();
    needsRegen = true;
}

function clearCanvas() { 
    ctx.clearRect(0, 0, canvas.width, canvas.height);   // clears canvas
}

// Function for drawing grid in current view
function drawGrid() {
    const v = view2d.view;
    const wWorld = v.xMax - v.xMin;
    // Picks nice grid spacing
    const step = niceStep(wWorld / 10);

    ctx.save();

    ctx.lineWidth = 1;
    ctx.strokeStyle = "rgba(0,0,0,0.08)";

    // Outer grid lines still visible in current view
    const xStart = Math.floor(v.xMin / step) * step;
    const xEnd = Math.ceil(v.xMax / step) * step;
    const yStart = Math.floor(v.yMin / step) * step;
    const yEnd = Math.ceil(v.yMax / step) * step;

    // Vertical grid lines
    for (let x = xStart; x <= xEnd; x += step) {
        const { px } = worldToCanvas(x, 0);
        ctx.beginPath();
        ctx.moveTo(px, 0);
        ctx.lineTo(px, canvas.height);
        ctx.stroke();
    }

    // Horizontal grid lines
    for (let y = yStart; y <= yEnd; y += step) {
        const { py } = worldToCanvas(0, y);
        ctx.beginPath();
        ctx.moveTo(0, py);
        ctx.lineTo(canvas.width, py);
        ctx.stroke();
    }

    ctx.restore();
}

function drawReferenceSquare() {
    // Draws original reference square
    const p00 = worldToCanvas(REF.p00.x, REF.p00.y);
    const p10 = worldToCanvas(REF.p10.x, REF.p10.y);
    const p11 = worldToCanvas(REF.p11.x, REF.p11.y);
    const p01 = worldToCanvas(REF.p01.x, REF.p01.y);

    ctx.save();

    ctx.lineWidth = 2;
    ctx.strokeStyle = "rgba(40, 120, 220, 0.45)";

    ctx.beginPath();
    ctx.moveTo(p00.px, p00.py);
    ctx.lineTo(p10.px, p10.py);
    ctx.lineTo(p11.px, p11.py);
    ctx.lineTo(p01.px, p01.py);
    ctx.closePath();
    ctx.stroke();

    ctx.restore();
}

function regenerateIfNeeded() {
    if (!needsRegen) return;

    // Regenerates attractor point cloud only if stale
    // Used to prevent recomputing all points on every redraw
    const n = Math.max(100, Math.floor(parseNumber(UI.numPoints().value, 10000)));
    cachedPoints = generateAffineFractal(affineMaps, n);
    needsRegen = false;
}

function drawPoints(points) {
    ctx.save();
    ctx.fillStyle = ink(0.95);

    for (const p of points) {
        const { px, py } = worldToCanvas(p.x, p.y);
        
        // Skips points outside visible canvas
        if (px < 0 || py < 0 || px >= canvas.width || py >= canvas.height) {
            continue;
        }
        // Draws cached attractor points
        ctx.fillRect(px, py, 1, 1);
    }
    
    ctx.restore();
}

function drawStepPoints() {
    if (!stepPoints.length) return;
    ctx.save();

    // Shows most recent step points s.t. overlay doesn't become too overwhelming
    const start = Math.max(0, stepPoints.length - 900);
    ctx.fillStyle = "rgba(239, 68, 68, 0.55)";     // red step-by-steo Chaos Game overlay
                                                    // shows how random orbit lands on attractor
    
    for (let i = start; i < stepPoints.length; i++) {
        const p = stepPoints[i];
        const { px, py } = worldToCanvas(p.x, p.y);
        ctx.fillRect(px - 1, py - 1, 3, 3);
    }

    // Highlights latest Chaos Game point
    const latest = stepPoints[stepPoints.length - 1];

    if (latest) {
        const { px, py } = worldToCanvas(latest.x, latest.y);
        
        ctx.beginPath();
        ctx.arc(px, py, 5, 0, Math.PI * 2);
        ctx.fillStyle = "rgba(220, 38, 38, 0.95)";
        ctx.fill();

        ctx.lineWidth = 2;
        ctx.strokeStyle = "rgba(255, 255, 255, 0.9)";
        ctx.stroke();
    }
    
    ctx.restore();
}

// Draws
function drawCorner(mapIndex, corner, pCanvas, rPx, color) {
    const isHover = hoverCorner && hoverCorner.mapIndex === mapIndex && hoverCorner.corner === corner;

    ctx.save();
    // Drawss one draggable corner handle
    ctx.beginPath();
    // Handle enlarges slightly when hovered
    ctx.arc(pCanvas.px, pCanvas.py, isHover ? rPx * 1.35 : rPx, 0, Math.PI * 2);

    ctx.fillStyle = color;
    ctx.fill();

    ctx.lineWidth = 2;
    ctx.strokeStyle = "rgba(255,255,255,0.92)";
    ctx.stroke();

    ctx.restore();
}

// Function draws editable iamge parallelogram for every affine map
// Key for visual editing interface
function drawMapParallelograms() {
    // Converts handle radius from world untis -> canvas pixels
    const rW = handleRadiusWorld();
    const rPx = (rW / (view2d.view.xMax - view2d.view.xMin)) * canvas.width;

    ctx.save();

    for (let i = 0; i < affineMaps.length; i++) {
        const m = affineMaps[i];
        // Gets four corners of the trnasformed reference square
        const { b, c1, c2, c12 } = imageParallelogram(m);

        // Converts each corner from world coordinates -> canvas coordinates
        const pb = worldToCanvas(b.x, b.y);
        const p1 = worldToCanvas(c1.x, c1.y);
        const p2 = worldToCanvas(c2.x, c2.y);
        const p12 = worldToCanvas(c12.x, c12.y);

        // Reference square image
        ctx.lineWidth = 2;
        ctx.strokeStyle = "rgba(220,40,40,0.30)";
        ctx.beginPath();
        ctx.moveTo(pb.px, pb.py);
        ctx.lineTo(p1.px, p1.py);
        ctx.lineTo(p12.px, p12.py);
        ctx.lineTo(p2.px, p2.py);
        ctx.closePath();
        ctx.stroke();

        // Draws diagonals s.t. parallelogram shape easier to use
        ctx.lineWidth = 1;
        ctx.strokeStyle = "rgba(0,0,0,0.10)";

        ctx.beginPath();
        ctx.moveTo(pb.px, pb.py); ctx.lineTo(p12.px, p12.py);
        ctx.moveTo(p1.px, p1.py); ctx.lineTo(p2.px, p2.py);
        ctx.stroke();

        // Draggable handles for each editable corner
        drawCorner(i, "b", pb, rPx, "rgba(220,40,40,0.95)");
        drawCorner(i, "c1", p1, rPx, "rgba(40,120,220,0.95)");
        drawCorner(i, "c2", p2, rPx, "rgba(40,180,120,0.95)");
        drawCorner(i, "c12", p12, rPx, "rgba(160,90,220,0.95)");

        // Map labels near base corner
        ctx.fillStyle = "rgba(0,0,0,0.55)";
        ctx.font 
            = "12px ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace";
        ctx.fillText(`f${i + 1}`, pb.px + 8, pb.py - 8);
    }
    
    ctx.restore();
}

function updateHUD(mouseWorld = null) {
    // Updates zoom readout
    if (UI.zoomIndicator()) {
        const initW = (view2d.initial.xMax - view2d.initial.xMin);
        const currW = (view2d.view.xMax - view2d.view.xMin);
        const z = initW / currW;
        
        UI.zoomIndicator().textContent = `Zoom: ${z.toFixed(2)}x`;
    }

    // Updates mouse coordinate readout
    if (UI.mouseCoords() && mouseWorld) {
        UI.mouseCoords().textContent 
            = `X: ${mouseWorld.x.toFixed(2)}, Y: ${mouseWorld.y.toFixed(2)}`;
    }

    // Updates status text
    if (statusReadout) {
        const pts = Math.max(100, Math.floor(parseNumber(UI.numPoints().value, 10000)));
        statusReadout.textContent = `Maps: ${affineMaps.length} | Points: ${pts}`;
    }

    // Diagonists stay live as maps change
    renderContractionWarnings();
}

// Full rendering for affine page
function render(mouseWorld = null) {
    view2d.resizeToDisplay({ trigger: false });

    clearCanvas();
    drawGrid();             // redraws grid
    drawReferenceSquare();  // redraws reference square

    regenerateIfNeeded();
    drawPoints(cachedPoints);   // attractor points

    drawStepPoints();           // step overlay
    drawMapParallelograms();    // draggable parallelogram

    // Updates UI readout
    updateHUD(mouseWorld);
}

function buildLabeledNumber(labelText, step, value, onInput) {
    // onInput callback received parsed numeric value
    const wrapper = document.createElement("label");
    wrapper.className = "mini-label";

    const label = document.createElement("span");
    label.textContent = labelText;

    // Builds labelled number input for editor panels
    const input = document.createElement("input");
    input.type = "number";
    input.step = step;
    input.value = fmt(value);

    input.addEventListener("input", () => {
        const v = parseFloat(input.value);

        // Ignores invalid v
        if (Number.isFinite(v)) {
            onInput(v, input);
        }
    });

    wrapper.append(label, input);
    return { wrapper, input };
}

function renderMatrixInputs() {
    const wrap = UI.matrixWrap();
    wrap.replaceChildren();

    affineMaps.forEach((m, i) => {
        const title = document.createElement("div");
        title.className = "mono";
        title.style.marginTop = "10px";
        title.textContent = `Map ${i + 1} - Matrix A`;

        wrap.appendChild(title);

        const row = document.createElement("div");
        row.className = "editor-grid-4";

        // Editing A changes image parallelogram and attractor
        // Input controls for every affine map
        row.append(
            buildLabeledNumber(`a11`, "0.001", m.a11, v => { 
                affineMaps[i].a11 = v; 
                applyProbabilityMode(); 
                needsRegen = true; 
                render(); 
                syncProbabilityInputs(); 
            }).wrapper,

            buildLabeledNumber(`a12`, "0.001", m.a12, v => { 
                affineMaps[i].a12 = v; 
                applyProbabilityMode(); 
                needsRegen = true; 
                render(); 
                syncProbabilityInputs(); 
            }).wrapper,

            buildLabeledNumber(`a21`, "0.001", m.a21, v => { 
                affineMaps[i].a21 = v; 
                applyProbabilityMode(); 
                needsRegen = true; 
                render(); 
                syncProbabilityInputs();
            }).wrapper,

            buildLabeledNumber(`a22`, "0.001", m.a22, v => { 
                affineMaps[i].a22 = v; 
                applyProbabilityMode(); 
                needsRegen = true; 
                render(); 
                syncProbabilityInputs();
            }).wrapper
        );

        wrap.appendChild(row);
    });
}

function renderVectorInputs() {
    const wrap = UI.vectorWrap();
    wrap.replaceChildren();

    affineMaps.forEach((m, i) => {
        const title = document.createElement("div");
        title.className = "mono";
        title.style.marginTop = "10px";
        title.textContent = `Map ${i + 1} - Vector b`;
        wrap.appendChild(title);

        const row = document.createElement("div");
        row.className = "editor-grid-2";

        // Editing b translated affine image
        // Input controls for every affine map
        row.append(
            buildLabeledNumber(`b1`, "0.001", m.b1, v => { 
                affineMaps[i].b1 = v; 
                needsRegen = true; 
                render();
            }).wrapper,

            buildLabeledNumber(`b2`, "0.001", m.b2, v => {
                affineMaps[i].b2 = v;
                needsRegen = true;
                render();
            }).wrapper
        );

        wrap.appendChild(row);
    });
}

// Function to render probability editor
function normaliseProbsUI() {
    const wrap = UI.probWrap();
    wrap.replaceChildren();
    
    let sum = 0;
    const mode = UI.probabilityMode()?.value || "custom";
    const isCustom = mode === "custom";

    affineMaps.forEach((m, i) => {
        const row = document.createElement("div");
        row.style.display = "grid";
        row.style.gridTemplateColumns = "1fr auto";
        row.style.gap = "10px";
        row.style.alignItems = "end";
        row.style.marginTop = "10px";

        const p = buildLabeledNumber(`p${i + 1}`, "0.001", m.prob, v => {
            // Manual probability edits switches back to custom mode
            // "custom" = can edit probabilities directly
            // "automatic" = probability fields disabled
            UI.probabilityMode().value = "custom";
            affineMaps[i].prob = Math.max(0, v);

            normaliseProbs();

            needsRegen = true;
            normaliseProbsUI();

            render();
        });

        // Disables probability inputs when probabilities generated automatically
        p.input.disabled = !isCustom;

        const badge = document.createElement("div");
        badge.className = "mono";
        badge.textContent = `||A|| ${fmt(spectralNorm(m), 3)}`;

        row.append(p.wrapper, badge);
        wrap.appendChild(row);

        sum += (+m.prob || 0);
    });

    const summary = document.createElement("div");
    summary.style.marginTop = "12px";
    summary.style.display = "flex";
    summary.style.gap = "10px";
    summary.style.alignItems = "center";

    const sumText = document.createElement("div");
    sumText.className = "mono";
    sumText.innerHTML = `Sum <strong>${sum.toFixed(4)}</strong>`;

    const btn = document.createElement("button");
    btn.type = "button";
    btn.className = "tiny-btn";
    btn.textContent = "Normalise";
    btn.disabled = !isCustom;

    btn.addEventListener("click", () => {
        normaliseProbs();

        needsRegen = true;
        normaliseProbsUI();

        render();
    });

    summary.append(sumText, btn);
    wrap.appendChild(summary);
}

// Function updates probability input values from affineMaps
function syncProbabilityInputs() {
    // Gets all probability inputs currently in UI
    const pInputs = UI.probWrap().querySelectorAll("input");
    // Copies each stored map probability to its matching input box
    for (let i = 0; i < affineMaps.length; i++) {
        if (pInputs[i]) pInputs[i].value = fmt(affineMaps[i].prob);
    }
}

// Function rebuilds all editor panels;
// Used when changing examples or map counts
function renderAllEditors() {
    UI.mapCount().value = String(affineMaps.length);

    renderMatrixInputs();
    renderVectorInputs();

    applyProbabilityMode();
    normaliseProbsUI();
    renderContractionWarnings();
}

function syncGizmoToInputs() {
    // Matrix inputs synced after dragging handle
    const mInputs = UI.matrixWrap().querySelectorAll("input");
    let k = 0;
    
    for (let i = 0; i < affineMaps.length; i++) {
        mInputs[k++].value = fmt(affineMaps[i].a11);
        mInputs[k++].value = fmt(affineMaps[i].a12);
        mInputs[k++].value = fmt(affineMaps[i].a21);
        mInputs[k++].value = fmt(affineMaps[i].a22);
    }

    // Vector inputs synced after dragging b
    const bInputs = UI.vectorWrap().querySelectorAll("input");
    k = 0;
    
    for (let i = 0; i < affineMaps.length; i++) {
        bInputs[k++].value = fmt(affineMaps[i].b1);
        bInputs[k++].value = fmt(affineMaps[i].b2);
    }

    // Ensures pnel values consistent with canvas gizmo
    applyProbabilityMode();
    syncProbabilityInputs();
    renderContractionWarnings();
}

// Starts dragging parallelogram before View2D's pan handler sees it
canvas.addEventListener("pointerdown", (e) => {
    canvas.setPointerCapture(e.pointerId);

    const { cx, cy } = clientToCanvasPx(e);
    const world = view2d.canvasPxToWorld(cx, cy);

    const picked = pickCorner(world);
    if (picked) {
        dragCorner = { 
            ...picked, 
            keepWhich: (e.shiftKey ? "c2" : "c1")   // Shift key changes which column stays fixed when dragging opposite corner
        };

        e.preventDefault();
        e.stopPropagation();

        return;
    }
}, true);

canvas.addEventListener("mousedown", (e) => {
    const { cx, cy } = clientToCanvasPx(e);
    const world = view2d.canvasPxToWorld(cx, cy);

    // Stops normal canvas panning if user clicked draggable corner
    if (pickCorner(world)) {
        e.preventDefault();
        e.stopImmediatePropagation();
    }
}, true);

canvas.addEventListener("pointermove", (e) => {
    const { cx, cy } = clientToCanvasPx(e);
    const world = view2d.canvasPxToWorld(cx, cy);

    // Updates hover state
    hoverCorner = pickCorner(world);

    if (dragCorner) {
        // Dragging directly edits selected affine map
        applyCornerDrag(
            dragCorner.mapIndex, 
            dragCorner.corner, world, 
            dragCorner.keepWhich
        );
        // Recalculates probabilities if depends on matrix sizes
        applyProbabilityMode();
        needsRegen = true;      // atrractor points don't match edited map now 
        syncGizmoToInputs();    // inputs synced with the dragged parallelogram
    }

    render(world);
}, { passive: true });

canvas.addEventListener("pointerup", () => {
    dragCorner = null;
    normaliseProbsUI();
});

canvas.addEventListener("pointercancel", () => {
    dragCorner = null;
    normaliseProbsUI();
});

canvas.addEventListener("contextmenu", (e) => {
    e.preventDefault();

    // Right-click zooms out around clicked point
    const { cx, cy } = clientToCanvasPx(e);
    const w = view2d.canvasPxToWorld(cx, cy);
    // Zooms-in at chosen point
    view2d.zoomAtWorldPoint(w.x, w.y, 1 / 1.35, { trigger: true });
});

// Dimensions:
// Function downsamples canvases to smaller temporary canvas
// Used for image-based dimension estimates
function downsampleToCanvas(srcCanvas, size) {
    const s = Math.max(128, size | 0);

    const off = document.createElement("canvas");
    off.width = s;
    off.height = s;

    // Converts visible canvas -> smaller bitmap
    const octx = off.getContext("2d", { willReadFrequently: true });
    octx.imageSmoothingEnabled = false;     // Keeps hard pixel edges rather than blurring mask
    
    octx.clearRect(0, 0, s, s);
    octx.drawImage(srcCanvas, 0, 0, s, s);
    
    return { octx, size: s };
}

// Builds binary mask from cavnas image data
function makeInkMaskFromImageData(img, w, h, { alphaMin = 16 } = {}) {
    const mask = new Uint8Array(w * h);
    const d = img.data;

    // Iterates through pixels
    for (let i = 0, px = 0; i < d.length; i += 4, px++) {
        const a = d[i + 3];
        mask[px] = a >= alphaMin ? 1 : 0;   // Any pixel with alpha >= alphaMin treated as occupied/ink
    }
    
    return mask;
}

// Function creates boundary mask from occupied mask
function makeBoundaryFromMask(mask, w, h) {
    const out = new Uint8Array(w * h);
    const idx = (x, y) => y * w + x;
    
    // Iterates through pixels
    // Skips outer border to avoid reading outside the array
    for (let y = 1; y < h - 1; y++) {
        for (let x = 1; x < w - 1; x++) {
            const i = idx(x, y);

            // Only occupied pixels can be part of boundary
            if (!mask[i]) continue;
            if (
                !mask[idx(x + 1, y)] || 
                !mask[idx(x - 1, y)] || 
                !mask[idx(x, y + 1)] || 
                !mask[idx(x, y - 1)]
            ) {
                // Pixel is boundary if it occupied & at least one of its direct neighbours is empty
                out[i] = 1;
            }
        }
    }

    return out;
}

function setDimReadout(result) {
    if (!result || !Number.isFinite(result.dimension)) {
        UI.dimValue().textContent = "-";
        UI.dimMeta().textContent = "Could not estimate (try changing box range / samples).";
        
        return;
    }

    const r2 = result.fit?.r2;
    // Updates dimension readout after DimensionLab finishes
    UI.dimValue().textContent = result.dimension.toFixed(4);
    UI.dimMeta().textContent
        = `${result.estimator}${Number.isFinite(r2) ? `, \\(R^2=${r2.toFixed(3)}\\)` : ""}`;
    typesetMath(UI.dimMeta());
}

// Function runs box-counting dimension estimation on current dendrite drawing
function runDimensionEstimate() {
    UI.dimValue().textContent = "...";
    UI.dimMeta().textContent = "Estimating...";

    // Reads estimator options from UI
    const ds = Math.max(128, parseNumber(UI.dimDownsample().value, 768) | 0);
    const minBox = Math.max(1, parseNumber(UI.dimMinBox().value, 2) | 0);
    const maxBox = Math.max(minBox + 1, parseNumber(UI.dimMaxBox().value, 256) | 0);
    const samples = Math.max(6, parseNumber(UI.dimSamples().value, 12) | 0);

    // Converts visible canvas -> smaller bitmap
    const { octx, size } = downsampleToCanvas(canvas, ds);
    const img = octx.getImageData(0, 0, size, size);

    // Ink mask marks occupied pixels
    const ink = makeInkMaskFromImageData(img, size, size, { alphaMin: 16 });
    // Chooses all visible ink OR only boundary pixels
    const bitmap = (UI.dimMode().value === "boundary") 
        ? makeBoundaryFromMask(ink, size, size) 
        : ink;

    try {
        const result = DimensionLab.run({
            estimator: "boxCountBitmap",
            input: {
                kind: "bitmap",
                data: { mask: bitmap, width: size, height: size },
                meta: { page: "affine" }
            },
            options: { minBox, maxBox, samples },
        });

        setDimReadout(result);
    } catch (err) {
        console.error(err);

        UI.dimValue().textContent = "-";
        UI.dimMeta().textContent = `Dimension error: ${err.message}`;
    }
}

UI.dimRunBtn()?.addEventListener("click", runDimensionEstimate);

// Animation loop function for visible Chaos-Game stepping
function animLoop() {
    if (!playing) return;

    // Adds several Chaos Game steps per frame s.t. animation visibly progresses
    stepMany(24);
    render();

    rafId = requestAnimationFrame(animLoop);
}

function stopAnim() {
    playing = false;

    if (rafId) {
        // Stops step animation
        cancelAnimationFrame(rafId);
    }
    rafId = null;

    // Resets play button label
    if (UI.toggleAnim()) {
        UI.toggleAnim().textContent = "Play";
    }
}

function stepMany(count = 1) {
    for (let i = 0; i < count; i++) {
        const map = chooseMap(affineMaps);

        currentPoint = applyAffine(currentPoint, map);
        // Advances step-by-step Chaos Game by count steps
        stepPoints.push({ ...currentPoint });
    }

    // Keeps only recent step points
    // Avoids endlessly growing overlay
    if (stepPoints.length > 2500) {
        stepPoints.splice(0, stepPoints.length - 2500);
    }
}

function stepOnce() {
    // Advances step-by-step Chaos Game once
    stepMany(1);
    render();       // redraws
}

function resetView() {
    // Resets view to default window for active example
    view2d.initial = { ...(exampleViews[activeExampleName] || DEFAULT_VIEW) };
    // Clears step overlay and regeneraets attractor
    view2d.setView(view2d.initial, { trigger: false });
    
    currentPoint = randomSeedPoint();
    stepPoints = [];
    needsRegen = true;

    render();
}

// === Main Buttons === //
UI.generate().addEventListener("click", () => { 
    applyProbabilityMode(); needsRegen = true; render(); 
});

UI.reset().addEventListener("click", () => { 
    stopAnim(); 
    resetView(); 
});

UI.export().addEventListener("click", () =>{
    exportCanvasPNG(canvas, "affine_ifs.png")
});

UI.clearSteps().addEventListener("click", () => { 
    currentPoint = randomSeedPoint(); 
    stepPoints = []; 
    render(); 
});

UI.stepOnce()?.addEventListener("click", () => {
    stopAnim();
    stepOnce();
});

UI.toggleAnim()?.addEventListener("click", () => {
    playing = !playing;
    UI.toggleAnim().textContent = playing ? "Pause" : "Play";

    if (playing) {
        animLoop();
    } else {
        stopAnim();
    }
});

UI.mapCount().addEventListener("input", (e) => {
    const desired = parseInt(e.target.value, 10);
    if (!Number.isFinite(desired)) return;
    ensureMapsLength(desired);
    
    renderAllEditors();
    needsRegen = true;
    render();
});

UI.numPoints().addEventListener("change", () => {
    // Number of Chaos Game points changed -> regenerates new render
    needsRegen = true;
    render();
});

UI.probabilityMode()?.addEventListener("change", () => {
    applyProbabilityMode();

    needsRegen = true;
    normaliseProbsUI();

    render();
});

UI.exampleSelector().addEventListener("change", (e) => {
    const name = e.target.value;
    if (!examples[name]) return;

    activeExampleName = name;
    // Copies example s.t. editing does not mutate preset
    affineMaps = JSON.parse(JSON.stringify(examples[name]));
    UI.probabilityMode().value = "custom";

    normaliseProbs();
    renderAllEditors();

    stopAnim();

    currentPoint = { x: 0, y: 0 };
    stepPoints = [];
    needsRegen = true;

    resetView();
});

function init() {
    view2d = new View2D({
        canvas,
        zoomIndicatorEl: UI.zoomIndicator(),
        mouseCoordsEl: UI.mouseCoords(),
        initial: DEFAULT_VIEW,
        enableDragPan: true,
        enableWheelZoom: true,
        enableClickZoom: false,
        enableRightClickZoom: true,
        
        // Redraws after zooming/panning, i.e. change to view
        onChange: () => render(),
    });

    view2d.resizeToDisplay({ trigger: false });

    // Loads default example
    affineMaps = JSON.parse(JSON.stringify(examples[activeExampleName]));
    normaliseProbs();
    renderAllEditors();     // builds editor

    resetView();
    render();               // performs first render
}

init();
